#!/bin/sh

#Authors: @Salaboy / @EstebanAliverti
kubectl $@

os=`uname`
if [ "${os}" = "Linux" ]
then
    date_cmd="date"
else
    date_cmd="gdate"
fi

if [ -z "$KUBECON" ]
then
    msg1= "Set the variable KUBECON with the next available conference. You can do this by running export KUBECON=2020/03/30 "    
else
    days="$(expr '(' $($date_cmd -d $KUBECON +%s) - $($date_cmd +%s) + 86399 ')' / 86400)";
    msg1=`echo "$days days for KubeCon! "`
fi
if [ -z "$KUBECONC4P" ]
then
    msg2= "Set the variable KUBECONC4P with the date of the C4P deadline. You can do this by running export KUBECONC4P=2019/12/04 "      
else
    days="$(expr '(' $($date_cmd -d $KUBECONC4P +%s) - $($date_cmd +%s) + 86399 ')' / 86400)";
    msg2=`echo "$days KubeCon C4P deadline"`
fi
(echo "$msg1\n\n$msg2") | cowsay -n 
